### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by bjtuwcy** [VincLee8188/GMAN-PyTorch#1]
Hello,is the meaning of the 78th lines in utils_.py  calculating the total seconds a day?I run your code,but this line is an error.

**Comment by VincLee8188** [comment]
I can't get the detailed error information from your question, but I guess the problem happened may be caused by the pandas version. You can replace  the line 78 'time.freq.delta.total_seconds()'  with '（5*60）'.
I hope that shall solve the problem you have met.
